defmodule AshMusicDb.Artist do
  @moduledoc """
  Add a change to the changeset:

  AshMusicDb.Artist |> Ash.Changeset.new() |> Ash.Changeset.change_attributes(%{name: "John Doe"})
  """

  # Using Ash.Resource turns this module into an Ash resource.
  use Ash.Resource,
    # Tells Ash where the generated code interface belongs
    domain: AshMusicDb,
    # Tells Ash you want this resource to store its data in Postgres.
    data_layer: AshPostgres.DataLayer

  postgres do
    # Tells Postgres what to call the table
    table "artists"
    # Tells Ash how to interface with the Postgres table
    repo(AshMusicDb.Repo)
  end

  actions do
    # Exposes default built in actions to manage the resource
    defaults [:read, :destroy]

    create :create do
      accept [:name]
    end

    update :update do
      accept [:name]
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    attribute :name, :string, do: allow_nil?(false)
    attribute :birth_date, :date
    attribute :death_date, :date

    create_timestamp :created_at
    update_timestamp :updated_at
  end
end
