defmodule AshMusicDb.Repo.Migrations.UpdateAlbumAddArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:albums) do
      add :artist_id,
          references(:artists,
            column: :id,
            name: "albums_artist_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:albums, "albums_artist_id_fkey")

    alter table(:albums) do
      remove :artist_id
    end
  end
end
