defmodule AshMusicDb.Repo.Migrations.UpdateAlbumAddTrack do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tracks) do
      add :album_id,
          references(:albums,
            column: :id,
            name: "tracks_album_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tracks, "tracks_album_id_fkey")

    alter table(:tracks) do
      remove :album_id
    end
  end
end
